# Generated by Django 5.2.17 on 2026-09-23 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_badge', models.CharField(default='New Arrivals & Trending', max_length=100)),
                ('hero_title', models.CharField(default='Discover Authentic Quality & Modern Elegance', max_length=255)),
                ('hero_description', models.TextField(default='Explore our curated collections of premium fashion, accessories, and essentials. Order directly with the shop owner via WhatsApp.')),
                ('hero_image', models.TextField(blank=True, default='')),
                ('hero_button_text', models.CharField(default='Shop Now', max_length=50)),
                ('about_title', models.CharField(default='About Shadas', max_length=255)),
                ('about_description', models.TextField(default='Welcome to Shadas. We are dedicated to bringing you top-tier quality products and a seamless, personalized shopping journey. With our direct WhatsApp ordering system, you get direct communication, custom support, and prompt delivery across Ghana.')),
                ('about_image', models.TextField(blank=True, default='')),
                ('about_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
                'db_table': 'homepage_content',
            },
        ),
    ]
