# Generated by Django 5.2.17 on 2026-09-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_description',
            field=models.TextField(default='Welcome to Shaddas. We are dedicated to bringing you top-tier quality products and a seamless, personalized shopping journey. With our direct WhatsApp ordering system, you get direct communication, custom support, and prompt delivery across Ghana.'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_title',
            field=models.CharField(default='About Shaddas', max_length=255),
        ),
    ]
