# Generated by Django 5.2.17 on 2026-09-23 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Shadas', max_length=255)),
                ('logo', models.TextField(blank=True, default='')),
                ('description', models.TextField(default='Discover premium quality products with direct WhatsApp ordering.')),
                ('whatsapp_number', models.CharField(default='+233 53 558 9099', max_length=50)),
                ('phone', models.CharField(default='+233 53 558 9099', max_length=50)),
                ('email', models.EmailField(default='contact@shadas.com', max_length=254)),
                ('location', models.CharField(default='Accra, Ghana', max_length=255)),
                ('instagram', models.CharField(blank=True, default='@shadas_official', max_length=100)),
                ('facebook', models.CharField(blank=True, default='shadas.store', max_length=100)),
                ('currency', models.CharField(default='GH₵', max_length=10)),
                ('currency_code', models.CharField(default='GHS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'db_table': 'shops',
            },
        ),
    ]
